package eu.bopet.jocadv.ie.step;

public class StepCode {
    static final String CARTESIAN_POINT = "CARTESIAN_POINT";
    static final String DIRECTION = "DIRECTION";
    static final String VECTOR = "VECTOR";
    static final String LINE = "LINE";
    static final String VERTEX_POINT = "VERTEX_POINT";
    static final String EDGE_CURVE = "EDGE_CURVE";
    static final String P_CURVE = "PCURVE";
    static final String AXIS2_PLACEMENT_3D = "AXIS2_PLACEMENT_3D";
    static final String PLANE = "PLANE";
    static final String ORIENTED_EDGE = "ORIENTED_EDGE";
    static final String SURFACE_CURVE = "SURFACE_CURVE";
    static final String EDGE_LOOP = "EDGE_LOOP";
    static final String FACE_BOUND = "FACE_BOUND";
    static final String ADVANCED_FACE = "ADVANCED_FACE";
    static final String CLOSED_SHELL = "CLOSED_SHELL";
    static final String MANIFOLD_SOLID_B_REP = "MANIFOLD_SOLID_BREP";
    static final String DEFINITIONAL_REPRESENTATION = "DEFINITIONAL_REPRESENTATION";
    static final String CYLINDRICAL_SURFACE = "CYLINDRICAL_SURFACE";
    static final String CIRCLE = "CIRCLE";
    static final String TOROIDAL_SURFACE = "TOROIDAL_SURFACE";
    static final String AXIS2_PLACEMENT_2D = "AXIS2_PLACEMENT_2D";
    static final String B_SPLINE_CURVE_WITH_KNOTS = "B_SPLINE_CURVE_WITH_KNOTS";
    static final String SEAM_CURVE = "SEAM_CURVE";
    static final String ELLIPSE = "ELLIPSE";
    static final String SURFACE_OF_LINEAR_EXTRUSION = "SURFACE_OF_LINEAR_EXTRUSION";
    static final String CONICAL_SURFACE = "CONICAL_SURFACE";
    static final String ADVANCED_BREP_SHAPE_REPRESENTATION = "ADVANCED_BREP_SHAPE_REPRESENTATION";
    static final String PRODUCT_DEFINITION_CONTEXT = "PRODUCT_DEFINITION_CONTEXT";
    static final String PRODUCT_CONTEXT = "PRODUCT_CONTEXT";
    static final String PRODUCT = "PRODUCT";
    static final String PRODUCT_DEFINITION_FORMATION = "PRODUCT_DEFINITION_FORMATION";
    static final String PRODUCT_DEFINITION = "PRODUCT_DEFINITION";
    static final String PRODUCT_DEFINITION_SHAPE = "PRODUCT_DEFINITION_SHAPE";
    static final String SHAPE_DEFINITION_REPRESENTATION = "SHAPE_DEFINITION_REPRESENTATION";
    static final String APPLICATION_CONTEXT = "APPLICATION_CONTEXT";
    static final String APPLICATION_PROTOCOL_DEFINITION = "APPLICATION_PROTOCOL_DEFINITION";
    static final String PRODUCT_CATEGORY = "PRODUCT_CATEGORY";
    static final String REPRESENTATION_CONTEXT = "REPRESENTATION_CONTEXT";

    static final String ANALYSIS_REPRESENTATION_CONTEXT = "ANALYSIS_REPRESENTATION_CONTEXT";
    static final String GEOMETRIC_REPRESENTATION_CONTEXT = "GEOMETRIC_REPRESENTATION_CONTEXT";
    static final String GEOMETRIC_REPRESENTATION_CONTEXT_WITH_PARAMETER
            = "GEOMETRIC_REPRESENTATION_CONTEXT_WITH_PARAMETER";
    static final String GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT = "GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT";
    static final String GLOBAL_UNIT_ASSIGNED_CONTEXT = "GLOBAL_UNIT_ASSIGNED_CONTEXT";
    static final String PARAMETRIC_REPRESENTATION_CONTEXT = "PARAMETRIC_REPRESENTATION_CONTEXT";
    static final String PATH_PARAMETRIC_REPRESENTATION_CONTEXT = "PATH_PARAMETRIC_REPRESENTATION_CONTEXT";
    static final String MECHANICAL_CONTEXT = "MECHANICAL_CONTEXT";
    static final String GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION =
            "GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION";
    static final String SHAPE_REPRESENTATION_RELATIONSHIP = "SHAPE_REPRESENTATION_RELATIONSHIP";
    static final String CC_DESIGN_APPROVAL = "CC_DESIGN_APPROVAL";
    static final String APPROVAL_PERSON_ORGANIZATION = "APPROVAL_PERSON_ORGANIZATION";
    static final String APPROVAL_ROLE = "APPROVAL_ROLE";
    static final String APPROVAL_DATE_TIME = "APPROVAL_DATE_TIME";
    static final String APPROVAL = "APPROVAL";
    static final String APPROVAL_STATUS = "APPROVAL_STATUS";
    static final String CC_DESIGN_SECURITY_CLASSIFICATION = "CC_DESIGN_SECURITY_CLASSIFICATION";
    static final String PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE =
            "PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE";
    static final String PRODUCT_RELATED_PRODUCT_CATEGORY = "PRODUCT_RELATED_PRODUCT_CATEGORY";
    static final String SHAPE_REPRESENTATION = "SHAPE_REPRESENTATION";
    static final String GEOMETRIC_CURVE_SET = "GEOMETRIC_CURVE_SET";
    static final String VERTEX_LOOP = "VERTEX_LOOP";
    static final String SPHERICAL_SURFACE = "SPHERICAL_SURFACE";
    static final String FACE_OUTER_BOUND = "FACE_OUTER_BOUND";
    static final String CURVE_STYLE = "CURVE_STYLE";
    static final String DRAUGHTING_PRE_DEFINED_CURVE_FONT = "DRAUGHTING_PRE_DEFINED_CURVE_FONT";
    static final String TRIMMED_CURVE = "TRIMMED_CURVE";
    static final String INVISIBILITY = "INVISIBILITY";
    static final String PRESENTATION_LAYER_ASSIGNMENT = "PRESENTATION_LAYER_ASSIGNMENT";
    static final String STYLED_ITEM = "STYLED_ITEM";
    static final String PRESENTATION_STYLE_ASSIGNMENT = "PRESENTATION_STYLE_ASSIGNMENT";

    public static final String[] REPRESENTATION_FOR_CONTEXT = {
            ANALYSIS_REPRESENTATION_CONTEXT,
            GEOMETRIC_REPRESENTATION_CONTEXT,
            GEOMETRIC_REPRESENTATION_CONTEXT_WITH_PARAMETER,
            GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT,
            GLOBAL_UNIT_ASSIGNED_CONTEXT,
            PARAMETRIC_REPRESENTATION_CONTEXT,
            PATH_PARAMETRIC_REPRESENTATION_CONTEXT,
            REPRESENTATION_CONTEXT
    };


}
