package eu.bopet.jocadv.ie.step;

public class StepCode {
    static final String ACTION = "ACTION";
    static final String ACTION_ASSIGNMENT = "ACTION_ASSIGNMENT";
    static final String ACTION_METHOD = "ACTION_METHOD";
    static final String ACTION_REQUEST_ASSIGNMENT = "ACTION_REQUEST_ASSIGNMENT";
    static final String ACTION_REQUEST_SOLUTION = "ACTION_REQUEST_SOLUTION";
    static final String ADDRESS = "ADDRESS";
    static final String ADVANCED_BREP_SHAPE_REPRESENTATION = "ADVANCED_BREP_SHAPE_REPRESENTATION";
    static final String ADVANCED_FACE = "ADVANCED_FACE";
    static final String ALIGNED_CURVE_3D_ELEMENT_COORDINATE_SYSTEM = "ALIGNED_CURVE_3D_ELEMENT_COORDINATE_SYSTEM";
    static final String ALIGNED_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM = "ALIGNED_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM";
    static final String ANALYSIS_ITEM_WITHIN_REPRESENTATION = "ANALYSIS_ITEM_WITHIN_REPRESENTATION";
    static final String ANALYSIS_REPRESENTATION_CONTEXT = "ANALYSIS_REPRESENTATION_CONTEXT";
    static final String ANGULARITY_TOLERANCE = "ANGULARITY_TOLERANCE";
    static final String ANGULAR_LOCATION = "ANGULAR_LOCATION";
    static final String ANGULAR_SIZE = "ANGULAR_SIZE";
    static final String ANNOTATION_CURVE_OCCURRENCE = "ANNOTATION_CURVE_OCCURRENCE";
    static final String ANNOTATION_FILL_AREA = "ANNOTATION_FILL_AREA";
    static final String ANNOTATION_FILL_AREA_OCCURRENCE = "ANNOTATION_FILL_AREA_OCCURRENCE";
    static final String ANNOTATION_OCCURRENCE = "ANNOTATION_OCCURRENCE";
    static final String ANNOTATION_SUBFIGURE_OCCURRENCE = "ANNOTATION_SUBFIGURE_OCCURRENCE";
    static final String ANNOTATION_SYMBOL = "ANNOTATION_SYMBOL";
    static final String ANNOTATION_SYMBOL_OCCURRENCE = "ANNOTATION_SYMBOL_OCCURRENCE";
    static final String ANNOTATION_TEXT = "ANNOTATION_TEXT";
    static final String ANNOTATION_TEXT_OCCURRENCE = "ANNOTATION_TEXT_OCCURRENCE";
    static final String APPLICATION_CONTEXT = "APPLICATION_CONTEXT";
    static final String APPLICATION_CONTEXT_ELEMENT = "APPLICATION_CONTEXT_ELEMENT";
    static final String APPLICATION_PROTOCOL_DEFINITION = "APPLICATION_PROTOCOL_DEFINITION";
    static final String APPLIED_APPROVAL_ASSIGNMENT = "APPLIED_APPROVAL_ASSIGNMENT";
    static final String APPLIED_DATE_AND_TIME_ASSIGNMENT = "APPLIED_DATE_AND_TIME_ASSIGNMENT";
    static final String APPLIED_DATE_ASSIGNMENT = "APPLIED_DATE_ASSIGNMENT";
    static final String APPLIED_DOCUMENT_REFERENCE = "APPLIED_DOCUMENT_REFERENCE";
    static final String APPLIED_EXTERNAL_IDENTIFICATION_ASSIGNMENT = "APPLIED_EXTERNAL_IDENTIFICATION_ASSIGNMENT";
    static final String APPLIED_GROUP_ASSIGNMENT = "APPLIED_GROUP_ASSIGNMENT";
    static final String APPLIED_ORGANIZATION_ASSIGNMENT = "APPLIED_ORGANIZATION_ASSIGNMENT";
    static final String APPLIED_PERSON_AND_ORGANIZATION_ASSIGNMENT = "APPLIED_PERSON_AND_ORGANIZATION_ASSIGNMENT";
    static final String APPLIED_PRESENTED_ITEM = "APPLIED_PRESENTED_ITEM";
    static final String APPLIED_SECURITY_CLASSIFICATION_ASSIGNMENT = "APPLIED_SECURITY_CLASSIFICATION_ASSIGNMENT";
    static final String APPROVAL = "APPROVAL";
    static final String APPROVAL_ASSIGNMENT = "APPROVAL_ASSIGNMENT";
    static final String APPROVAL_DATE_TIME = "APPROVAL_DATE_TIME";
    static final String APPROVAL_PERSON_ORGANIZATION = "APPROVAL_PERSON_ORGANIZATION";
    static final String APPROVAL_RELATIONSHIP = "APPROVAL_RELATIONSHIP";
    static final String APPROVAL_ROLE = "APPROVAL_ROLE";
    static final String APPROVAL_STATUS = "APPROVAL_STATUS";
    static final String ARBITRARY_VOLUME_3D_ELEMENT_COORDINATE_SYSTEM = "ARBITRARY_VOLUME_3D_ELEMENT_COORDINATE_SYSTEM";
    static final String AREA_IN_SET = "AREA_IN_SET";
    static final String AREA_UNIT = "AREA_UNIT";
    static final String ASSEMBLY_COMPONENT_USAGE = "ASSEMBLY_COMPONENT_USAGE";
    static final String ASSEMBLY_COMPONENT_USAGE_SUBSTITUTE = "ASSEMBLY_COMPONENT_USAGE_SUBSTITUTE";
    static final String AUTO_DESIGN_ACTUAL_DATE_AND_TIME_ASSIGNMENT = "AUTO_DESIGN_ACTUAL_DATE_AND_TIME_ASSIGNMENT";
    static final String AUTO_DESIGN_ACTUAL_DATE_ASSIGNMENT = "AUTO_DESIGN_ACTUAL_DATE_ASSIGNMENT";
    static final String AUTO_DESIGN_APPROVAL_ASSIGNMENT = "AUTO_DESIGN_APPROVAL_ASSIGNMENT";
    static final String AUTO_DESIGN_DATE_AND_PERSON_ASSIGNMENT = "AUTO_DESIGN_DATE_AND_PERSON_ASSIGNMENT";
    static final String AUTO_DESIGN_DOCUMENT_REFERENCE = "AUTO_DESIGN_DOCUMENT_REFERENCE";
    static final String AUTO_DESIGN_GROUP_ASSIGNMENT = "AUTO_DESIGN_GROUP_ASSIGNMENT";
    static final String AUTO_DESIGN_NOMINAL_DATE_AND_TIME_ASSIGNMENT = "AUTO_DESIGN_NOMINAL_DATE_AND_TIME_ASSIGNMENT";
    static final String AUTO_DESIGN_NOMINAL_DATE_ASSIGNMENT = "AUTO_DESIGN_NOMINAL_DATE_ASSIGNMENT";
    static final String AUTO_DESIGN_ORGANIZATION_ASSIGNMENT = "AUTO_DESIGN_ORGANIZATION_ASSIGNMENT";
    static final String AUTO_DESIGN_PERSON_AND_ORGANIZATION_ASSIGNMENT = "AUTO_DESIGN_PERSON_AND_ORGANIZATION_ASSIGNMENT";
    static final String AUTO_DESIGN_PRESENTED_ITEM = "AUTO_DESIGN_PRESENTED_ITEM";
    static final String AUTO_DESIGN_SECURITY_CLASSIFICATION_ASSIGNMENT = "AUTO_DESIGN_SECURITY_CLASSIFICATION_ASSIGNMENT";
    static final String AUTO_DESIGN_VIEW_AREA = "AUTO_DESIGN_VIEW_AREA";
    static final String AXIS1_PLACEMENT = "AXIS1_PLACEMENT";
    static final String AXIS2_PLACEMENT_2D = "AXIS2_PLACEMENT_2D";
    static final String AXIS2_PLACEMENT_3D = "AXIS2_PLACEMENT_3D";
    static final String BACKGROUND_COLOUR = "BACKGROUND_COLOUR";
    static final String BEZIER_CURVE = "BEZIER_CURVE";
    static final String BEZIER_SURFACE = "BEZIER_SURFACE";
    static final String BLOCK = "BLOCK";
    static final String BOOLEAN_RESULT = "BOOLEAN_RESULT";
    static final String BOUNDARY_CURVE = "BOUNDARY_CURVE";
    static final String BOUNDED_CURVE = "BOUNDED_CURVE";
    static final String BOUNDED_SURFACE = "BOUNDED_SURFACE";
    static final String BOXED_HALF_SPACE = "BOXED_HALF_SPACE";
    static final String BOX_DOMAIN = "BOX_DOMAIN";
    static final String BREP_WITH_VOIDS = "BREP_WITH_VOIDS";
    static final String B_SPLINE_CURVE = "B_SPLINE_CURVE";
    static final String B_SPLINE_CURVE_WITH_KNOTS = "B_SPLINE_CURVE_WITH_KNOTS";
    static final String B_SPLINE_SURFACE = "B_SPLINE_SURFACE";
    static final String B_SPLINE_SURFACE_WITH_KNOTS = "B_SPLINE_SURFACE_WITH_KNOTS";
    static final String CALENDAR_DATE = "CALENDAR_DATE";
    static final String CAMERA_IMAGE = "CAMERA_IMAGE";
    static final String CAMERA_IMAGE_2D_WITH_SCALE = "CAMERA_IMAGE_2D_WITH_SCALE";
    static final String CAMERA_IMAGE_3D_WITH_SCALE = "CAMERA_IMAGE_3D_WITH_SCALE";
    static final String CAMERA_MODEL = "CAMERA_MODEL";
    static final String CAMERA_MODEL_D2 = "CAMERA_MODEL_D2";
    static final String CAMERA_MODEL_D3 = "CAMERA_MODEL_D3";
    static final String CAMERA_USAGE = "CAMERA_USAGE";
    static final String CARTESIAN_POINT = "CARTESIAN_POINT";
    static final String CARTESIAN_TRANSFORMATION_OPERATOR = "CARTESIAN_TRANSFORMATION_OPERATOR";
    static final String CARTESIAN_TRANSFORMATION_OPERATOR_2D = "CARTESIAN_TRANSFORMATION_OPERATOR_2D";
    static final String CARTESIAN_TRANSFORMATION_OPERATOR_3D = "CARTESIAN_TRANSFORMATION_OPERATOR_3D";
    static final String CC_DESIGN_APPROVAL = "CC_DESIGN_APPROVAL";
    static final String CC_DESIGN_CERTIFICATION = "CC_DESIGN_CERTIFICATION";
    static final String CC_DESIGN_CONTRACT = "CC_DESIGN_CONTRACT";
    static final String CC_DESIGN_DATE_AND_TIME_ASSIGNMENT = "CC_DESIGN_DATE_AND_TIME_ASSIGNMENT";
    static final String CC_DESIGN_PERSON_AND_ORGANIZATION_ASSIGNMENT = "CC_DESIGN_PERSON_AND_ORGANIZATION_ASSIGNMENT";
    static final String CC_DESIGN_SECURITY_CLASSIFICATION = "CC_DESIGN_SECURITY_CLASSIFICATION";
    static final String CC_DESIGN_SPECIFICATION_REFERENCE = "CC_DESIGN_SPECIFICATION_REFERENCE";
    static final String CERTIFICATION = "CERTIFICATION";
    static final String CERTIFICATION_ASSIGNMENT = "CERTIFICATION_ASSIGNMENT";
    static final String CERTIFICATION_TYPE = "CERTIFICATION_TYPE";
    static final String CHANGE = "CHANGE";
    static final String CHANGE_REQUEST = "CHANGE_REQUEST";
    static final String CHARACTERIZED_OBJECT = "CHARACTERIZED_OBJECT";
    static final String CIRCLE = "CIRCLE";
    static final String CIRCULAR_RUNOUT_TOLERANCE = "CIRCULAR_RUNOUT_TOLERANCE";
    static final String CLASS = "CLASS";
    static final String CLOSED_SHELL = "CLOSED_SHELL";
    static final String COAXIALITY_TOLERANCE = "COAXIALITY_TOLERANCE";
    static final String COLOUR = "COLOUR";
    static final String COLOUR_RGB = "COLOUR_RGB";
    static final String COLOUR_SPECIFICATION = "COLOUR_SPECIFICATION";
    static final String COMMON_DATUM = "COMMON_DATUM";
    static final String COMPOSITE_CURVE = "COMPOSITE_CURVE";
    static final String COMPOSITE_CURVE_ON_SURFACE = "COMPOSITE_CURVE_ON_SURFACE";
    static final String COMPOSITE_CURVE_SEGMENT = "COMPOSITE_CURVE_SEGMENT";
    static final String COMPOSITE_SHAPE_ASPECT = "COMPOSITE_SHAPE_ASPECT";
    static final String COMPOSITE_TEXT = "COMPOSITE_TEXT";
    static final String COMPOSITE_TEXT_WITH_ASSOCIATED_CURVES = "COMPOSITE_TEXT_WITH_ASSOCIATED_CURVES";
    static final String COMPOSITE_TEXT_WITH_BLANKING_BOX = "COMPOSITE_TEXT_WITH_BLANKING_BOX";
    static final String COMPOSITE_TEXT_WITH_EXTENT = "COMPOSITE_TEXT_WITH_EXTENT";
    static final String COMPOUND_REPRESENTATION_ITEM = "COMPOUND_REPRESENTATION_ITEM";
    static final String COMPOUND_SHAPE_REPRESENTATION = "COMPOUND_SHAPE_REPRESENTATION";
    static final String CONCENTRICITY_TOLERANCE = "CONCENTRICITY_TOLERANCE";
    static final String CONFIGURATION_DESIGN = "CONFIGURATION_DESIGN";
    static final String CONFIGURATION_EFFECTIVITY = "CONFIGURATION_EFFECTIVITY";
    static final String CONIC = "CONIC";
    static final String CONICAL_SURFACE = "CONICAL_SURFACE";
    static final String CONNECTED_EDGE_SET = "CONNECTED_EDGE_SET";
    static final String CONNECTED_FACE_SET = "CONNECTED_FACE_SET";
    static final String CONNECTED_FACE_SHAPE_REPRESENTATION = "CONNECTED_FACE_SHAPE_REPRESENTATION";
    static final String CONNECTED_FACE_SUB_SET = "CONNECTED_FACE_SUB_SET";
    static final String CONSTANT_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM = "CONSTANT_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM";
    static final String CONTEXT_DEPENDENT_INVISIBILITY = "CONTEXT_DEPENDENT_INVISIBILITY";
    static final String CONTEXT_DEPENDENT_OVER_RIDING_STYLED_ITEM = "CONTEXT_DEPENDENT_OVER_RIDING_STYLED_ITEM";
    static final String CONTEXT_DEPENDENT_SHAPE_REPRESENTATION = "CONTEXT_DEPENDENT_SHAPE_REPRESENTATION";
    static final String CONTRACT = "CONTRACT";
    static final String CONTRACT_ASSIGNMENT = "CONTRACT_ASSIGNMENT";
    static final String CONTRACT_TYPE = "CONTRACT_TYPE";
    static final String CONVERSION_BASED_UNIT = "CONVERSION_BASED_UNIT";
    static final String COORDINATED_UNIVERSAL_TIME_OFFSET = "COORDINATED_UNIVERSAL_TIME_OFFSET";
    static final String CSG_REPRESENTATION = "CSG_REPRESENTATION";
    static final String CSG_SHAPE_REPRESENTATION = "CSG_SHAPE_REPRESENTATION";
    static final String CSG_SOLID = "CSG_SOLID";
    static final String CURVE = "CURVE";
    static final String CURVE_3D_ELEMENT_DESCRIPTOR = "CURVE_3D_ELEMENT_DESCRIPTOR";
    static final String CURVE_3D_ELEMENT_PROPERTY = "CURVE_3D_ELEMENT_PROPERTY";
    static final String CURVE_3D_ELEMENT_REPRESENTATION = "CURVE_3D_ELEMENT_REPRESENTATION";
    static final String CURVE_BOUNDED_SURFACE = "CURVE_BOUNDED_SURFACE";
    static final String CURVE_ELEMENT_END_OFFSET = "CURVE_ELEMENT_END_OFFSET";
    static final String CURVE_ELEMENT_END_RELEASE = "CURVE_ELEMENT_END_RELEASE";
    static final String CURVE_ELEMENT_END_RELEASE_PACKET = "CURVE_ELEMENT_END_RELEASE_PACKET";
    static final String CURVE_ELEMENT_INTERVAL = "CURVE_ELEMENT_INTERVAL";
    static final String CURVE_ELEMENT_INTERVAL_CONSTANT = "CURVE_ELEMENT_INTERVAL_CONSTANT";
    static final String CURVE_ELEMENT_INTERVAL_LINEARLY_VARYING = "CURVE_ELEMENT_INTERVAL_LINEARLY_VARYING";
    static final String CURVE_ELEMENT_LOCATION = "CURVE_ELEMENT_LOCATION";
    static final String CURVE_ELEMENT_SECTION_DEFINITION = "CURVE_ELEMENT_SECTION_DEFINITION";
    static final String CURVE_ELEMENT_SECTION_DERIVED_DEFINITIONS = "CURVE_ELEMENT_SECTION_DERIVED_DEFINITIONS";
    static final String CURVE_REPLICA = "CURVE_REPLICA";
    static final String CURVE_STYLE = "CURVE_STYLE";
    static final String CURVE_STYLE_FONT = "CURVE_STYLE_FONT";
    static final String CURVE_STYLE_FONT_PATTERN = "CURVE_STYLE_FONT_PATTERN";
    static final String CYLINDRICAL_SURFACE = "CYLINDRICAL_SURFACE";
    static final String DATA_ENVIRONMENT = "DATA_ENVIRONMENT";
    static final String DATE = "DATE";
    static final String DATE_AND_TIME = "DATE_AND_TIME";
    static final String DATE_AND_TIME_ASSIGNMENT = "DATE_AND_TIME_ASSIGNMENT";
    static final String DATE_ASSIGNMENT = "DATE_ASSIGNMENT";
    static final String DATE_ROLE = "DATE_ROLE";
    static final String DATE_TIME_ROLE = "DATE_TIME_ROLE";
    static final String DATUM = "DATUM";
    static final String DATUM_FEATURE = "DATUM_FEATURE";
    static final String DATUM_REFERENCE = "DATUM_REFERENCE";
    static final String DATUM_TARGET = "DATUM_TARGET";
    static final String DEFINED_SYMBOL = "DEFINED_SYMBOL";
    static final String DEFINITIONAL_REPRESENTATION = "DEFINITIONAL_REPRESENTATION";
    static final String DEGENERATE_PCURVE = "DEGENERATE_PCURVE";
    static final String DEGENERATE_TOROIDAL_SURFACE = "DEGENERATE_TOROIDAL_SURFACE";
    static final String DERIVED_SHAPE_ASPECT = "DERIVED_SHAPE_ASPECT";
    static final String DERIVED_UNIT = "DERIVED_UNIT";
    static final String DERIVED_UNIT_ELEMENT = "DERIVED_UNIT_ELEMENT";
    static final String DESCRIPTIVE_REPRESENTATION_ITEM = "DESCRIPTIVE_REPRESENTATION_ITEM";
    static final String DESIGN_CONTEXT = "DESIGN_CONTEXT";
    static final String DIGITAL_DOCUMENT = "DIGITAL_DOCUMENT";
    static final String DIMENSIONAL_CHARACTERISTIC_REPRESENTATION = "DIMENSIONAL_CHARACTERISTIC_REPRESENTATION";
    static final String DIMENSIONAL_EXPONENTS = "DIMENSIONAL_EXPONENTS";
    static final String DIMENSIONAL_LOCATION = "DIMENSIONAL_LOCATION";
    static final String DIMENSIONAL_LOCATION_WITH_PATH = "DIMENSIONAL_LOCATION_WITH_PATH";
    static final String DIMENSIONAL_SIZE = "DIMENSIONAL_SIZE";
    static final String DIMENSIONAL_SIZE_WITH_PATH = "DIMENSIONAL_SIZE_WITH_PATH";
    static final String DIMENSION_CURVE = "DIMENSION_CURVE";
    static final String DIMENSION_CURVE_TERMINATOR = "DIMENSION_CURVE_TERMINATOR";
    static final String DIRECTED_DIMENSIONAL_LOCATION = "DIRECTED_DIMENSIONAL_LOCATION";
    static final String DIRECTION = "DIRECTION";
    static final String DOCUMENT = "DOCUMENT";
    static final String DOCUMENT_FILE = "DOCUMENT_FILE";
    static final String DOCUMENT_PRODUCT_ASSOCIATION = "DOCUMENT_PRODUCT_ASSOCIATION";
    static final String DOCUMENT_PRODUCT_EQUIVALENCE = "DOCUMENT_PRODUCT_EQUIVALENCE";
    static final String DOCUMENT_RELATIONSHIP = "DOCUMENT_RELATIONSHIP";
    static final String DOCUMENT_REPRESENTATION_TYPE = "DOCUMENT_REPRESENTATION_TYPE";
    static final String DOCUMENT_TYPE = "DOCUMENT_TYPE";
    static final String DOCUMENT_USAGE_CONSTRAINT = "DOCUMENT_USAGE_CONSTRAINT";
    static final String DRAUGHTING_ANNOTATION_OCCURRENCE = "DRAUGHTING_ANNOTATION_OCCURRENCE";
    static final String DRAUGHTING_CALLOUT = "DRAUGHTING_CALLOUT";
    static final String DRAUGHTING_MODEL = "DRAUGHTING_MODEL";
    static final String DRAUGHTING_PRE_DEFINED_COLOUR = "DRAUGHTING_PRE_DEFINED_COLOUR";
    static final String DRAUGHTING_PRE_DEFINED_CURVE_FONT = "DRAUGHTING_PRE_DEFINED_CURVE_FONT";
    static final String DRAUGHTING_SUBFIGURE_REPRESENTATION = "DRAUGHTING_SUBFIGURE_REPRESENTATION";
    static final String DRAUGHTING_SYMBOL_REPRESENTATION = "DRAUGHTING_SYMBOL_REPRESENTATION";
    static final String DRAUGHTING_TEXT_LITERAL_WITH_DELINEATION = "DRAUGHTING_TEXT_LITERAL_WITH_DELINEATION";
    static final String DRAWING_DEFINITION = "DRAWING_DEFINITION";
    static final String DRAWING_REVISION = "DRAWING_REVISION";
    static final String DUMMY_NODE = "DUMMY_NODE";
    static final String EDGE = "EDGE";
    static final String EDGE_BASED_WIREFRAME_MODEL = "EDGE_BASED_WIREFRAME_MODEL";
    static final String EDGE_BASED_WIREFRAME_SHAPE_REPRESENTATION = "EDGE_BASED_WIREFRAME_SHAPE_REPRESENTATION";
    static final String EDGE_CURVE = "EDGE_CURVE";
    static final String EDGE_LOOP = "EDGE_LOOP";
    static final String EFFECTIVITY = "EFFECTIVITY";
    static final String EFFECTIVITY_ASSIGNMENT = "EFFECTIVITY_ASSIGNMENT";
    static final String ELEMENTARY_SURFACE = "ELEMENTARY_SURFACE";
    static final String ELEMENT_DESCRIPTOR = "ELEMENT_DESCRIPTOR";
    static final String ELEMENT_GEOMETRIC_RELATIONSHIP = "ELEMENT_GEOMETRIC_RELATIONSHIP";
    static final String ELEMENT_GROUP = "ELEMENT_GROUP";
    static final String ELEMENT_MATERIAL = "ELEMENT_MATERIAL";
    static final String ELEMENT_REPRESENTATION = "ELEMENT_REPRESENTATION";
    static final String ELLIPSE = "ELLIPSE";
    static final String EULER_ANGLES = "EULER_ANGLES";
    static final String EVALUATED_DEGENERATE_PCURVE = "EVALUATED_DEGENERATE_PCURVE";
    static final String EXTENSION = "EXTENSION";
    static final String EXTERNALLY_DEFINED_CURVE_FONT = "EXTERNALLY_DEFINED_CURVE_FONT";
    static final String EXTERNALLY_DEFINED_Class = "EXTERNALLY_DEFINED_Class";
    static final String EXTERNALLY_DEFINED_GENERAL_PROPERTY = "EXTERNALLY_DEFINED_GENERAL_PROPERTY";
    static final String EXTERNALLY_DEFINED_HATCH_STYLE = "EXTERNALLY_DEFINED_HATCH_STYLE";
    static final String EXTERNALLY_DEFINED_ITEM = "EXTERNALLY_DEFINED_ITEM";
    static final String EXTERNALLY_DEFINED_REPRESENTATION = "EXTERNALLY_DEFINED_REPRESENTATION";
    static final String EXTERNALLY_DEFINED_SYMBOL = "EXTERNALLY_DEFINED_SYMBOL";
    static final String EXTERNALLY_DEFINED_TEXT_FONT = "EXTERNALLY_DEFINED_TEXT_FONT";
    static final String EXTERNALLY_DEFINED_TILE_STYLE = "EXTERNALLY_DEFINED_TILE_STYLE";
    static final String EXTERNAL_IDENTIFICATION_ASSIGNMENT = "EXTERNAL_IDENTIFICATION_ASSIGNMENT";
    static final String EXTERNAL_SOURCE = "EXTERNAL_SOURCE";
    static final String EXTRUDED_AREA_SOLID = "EXTRUDED_AREA_SOLID";
    static final String EXTRUDED_FACE_SOLID = "EXTRUDED_FACE_SOLID";
    static final String FACE = "FACE";
    static final String FACETED_BREP = "FACETED_BREP";
    static final String FACETED_BREP_SHAPE_REPRESENTATION = "FACETED_BREP_SHAPE_REPRESENTATION";
    static final String FACE_BASED_SURFACE_MODEL = "FACE_BASED_SURFACE_MODEL";
    static final String FACE_BOUND = "FACE_BOUND";
    static final String FACE_OUTER_BOUND = "FACE_OUTER_BOUND";
    static final String FACE_SURFACE = "FACE_SURFACE";
    static final String FEA_AREA_DENSITY = "FEA_AREA_DENSITY";
    static final String FEA_AXIS2_PLACEMENT_3D = "FEA_AXIS2_PLACEMENT_3D";
    static final String FEA_CURVE_SECTION_GEOMETRIC_RELATIONSHIP = "FEA_CURVE_SECTION_GEOMETRIC_RELATIONSHIP";
    static final String FEA_GROUP = "FEA_GROUP";
    static final String FEA_LINEAR_ELASTICITY = "FEA_LINEAR_ELASTICITY";
    static final String FEA_MASS_DENSITY = "FEA_MASS_DENSITY";
    static final String FEA_MATERIAL_PROPERTY_REPRESENTATION = "FEA_MATERIAL_PROPERTY_REPRESENTATION";
    static final String FEA_MATERIAL_PROPERTY_REPRESENTATION_ITEM = "FEA_MATERIAL_PROPERTY_REPRESENTATION_ITEM";
    static final String FEA_MODEL = "FEA_MODEL";
    static final String FEA_MODEL_3D = "FEA_MODEL_3D";
    static final String FEA_MODEL_DEFINITION = "FEA_MODEL_DEFINITION";
    static final String FEA_MOISTURE_ABSORPTION = "FEA_MOISTURE_ABSORPTION";
    static final String FEA_PARAMETRIC_POINT = "FEA_PARAMETRIC_POINT";
    static final String FEA_REPRESENTATION_ITEM = "FEA_REPRESENTATION_ITEM";
    static final String FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION = "FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION";
    static final String FEA_SHELL_BENDING_STIFFNESS = "FEA_SHELL_BENDING_STIFFNESS";
    static final String FEA_SHELL_MEMBRANE_BENDING_COUPLING_STIFFNESS = "FEA_SHELL_MEMBRANE_BENDING_COUPLING_STIFFNESS";
    static final String FEA_SHELL_MEMBRANE_STIFFNESS = "FEA_SHELL_MEMBRANE_STIFFNESS";
    static final String FEA_SHELL_SHEAR_STIFFNESS = "FEA_SHELL_SHEAR_STIFFNESS";
    static final String FEA_SURFACE_SECTION_GEOMETRIC_RELATIONSHIP = "FEA_SURFACE_SECTION_GEOMETRIC_RELATIONSHIP";
    static final String FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION = "FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION";
    static final String FILL_AREA_STYLE = "FILL_AREA_STYLE";
    static final String FILL_AREA_STYLE_COLOUR = "FILL_AREA_STYLE_COLOUR";
    static final String FILL_AREA_STYLE_HATCHING = "FILL_AREA_STYLE_HATCHING";
    static final String FILL_AREA_STYLE_TILES = "FILL_AREA_STYLE_TILES";
    static final String FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE = "FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE";
    static final String FLATNESS_TOLERANCE = "FLATNESS_TOLERANCE";
    static final String FREEDOMS_LIST = "FREEDOMS_LIST";
    static final String FREEDOM_AND_COEFFICIENT = "FREEDOM_AND_COEFFICIENT";
    static final String FUNCTIONALLY_DEFINED_TRANSFORMATION = "FUNCTIONALLY_DEFINED_TRANSFORMATION";
    static final String GENERAL_PROPERTY = "GENERAL_PROPERTY";
    static final String GEOMETRICALLY_BOUNDED_SURFACE_SHAPE_REPRESENTATION = "GEOMETRICALLY_BOUNDED_SURFACE_SHAPE_REPRESENTATION";
    static final String GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION = "GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION";
    static final String GEOMETRIC_CURVE_SET = "GEOMETRIC_CURVE_SET";
    static final String GEOMETRIC_NODE = "GEOMETRIC_NODE";
    static final String GEOMETRIC_REPRESENTATION_CONTEXT = "GEOMETRIC_REPRESENTATION_CONTEXT";
    static final String GEOMETRIC_REPRESENTATION_CONTEXT_WITH_PARAMETER
            = "GEOMETRIC_REPRESENTATION_CONTEXT_WITH_PARAMETER";
    static final String GEOMETRIC_REPRESENTATION_ITEM = "GEOMETRIC_REPRESENTATION_ITEM";
    static final String GEOMETRIC_SET = "GEOMETRIC_SET";
    static final String GEOMETRIC_TOLERANCE = "GEOMETRIC_TOLERANCE";
    static final String GEOMETRIC_TOLERANCE_RELATIONSHIP = "GEOMETRIC_TOLERANCE_RELATIONSHIP";
    static final String GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE = "GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE";
    static final String GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT = "GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT";
    static final String GLOBAL_UNIT_ASSIGNED_CONTEXT = "GLOBAL_UNIT_ASSIGNED_CONTEXT";
    static final String GROUP = "GROUP";
    static final String GROUP_ASSIGNMENT = "GROUP_ASSIGNMENT";
    static final String GROUP_RELATIONSHIP = "GROUP_RELATIONSHIP";
    static final String HALF_SPACE_SOLID = "HALF_SPACE_SOLID";
    static final String HYPERBOLA = "HYPERBOLA";
    static final String IDENTIFICATION_ASSIGNMENT = "IDENTIFICATION_ASSIGNMENT";
    static final String IDENTIFICATION_ROLE = "IDENTIFICATION_ROLE";
    static final String INTERSECTION_CURVE = "INTERSECTION_CURVE";
    static final String INVISIBILITY = "INVISIBILITY";
    static final String ITEM_DEFINED_TRANSFORMATION = "ITEM_DEFINED_TRANSFORMATION";
    static final String LENGTH_MEASURE_WITH_UNIT = "LENGTH_MEASURE_WITH_UNIT";
    static final String LENGTH_UNIT = "LENGTH_UNIT";
    static final String LIMITS_AND_FITS = "LIMITS_AND_FITS";
    static final String LINE = "LINE";
    static final String LINE_PROFILE_TOLERANCE = "LINE_PROFILE_TOLERANCE";
    static final String LOCAL_TIME = "LOCAL_TIME";
    static final String LOOP = "LOOP";
    static final String MAKE_FROM_USAGE_OPTION = "MAKE_FROM_USAGE_OPTION";
    static final String MANIFOLD_SOLID_BREP = "MANIFOLD_SOLID_BREP";
    static final String MANIFOLD_SURFACE_SHAPE_REPRESENTATION = "MANIFOLD_SURFACE_SHAPE_REPRESENTATION";
    static final String MAPPED_ITEM = "MAPPED_ITEM";
    static final String MASS_MEASURE_WITH_UNIT = "MASS_MEASURE_WITH_UNIT";
    static final String MASS_UNIT = "MASS_UNIT";
    static final String MATERIAL_DESIGNATION = "MATERIAL_DESIGNATION";
    static final String MATERIAL_PROPERTY = "MATERIAL_PROPERTY";
    static final String MATERIAL_PROPERTY_REPRESENTATION = "MATERIAL_PROPERTY_REPRESENTATION";
    static final String MEASURE_QUALIFICATION = "MEASURE_QUALIFICATION";
    static final String MEASURE_REPRESENTATION_ITEM = "MEASURE_REPRESENTATION_ITEM";
    static final String MEASURE_WITH_UNIT = "MEASURE_WITH_UNIT";
    static final String MECHANICAL_CONTEXT = "MECHANICAL_CONTEXT";
    static final String MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_AREA = "MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_AREA";
    static final String MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION = "MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION";
    static final String MECHANICAL_DESIGN_PRESENTATION_AREA = "MECHANICAL_DESIGN_PRESENTATION_AREA";
    static final String MODIFIED_GEOMETRIC_TOLERANCE = "MODIFIED_GEOMETRIC_TOLERANCE";
    static final String NAMED_UNIT = "NAMED_UNIT";
    static final String NAME_ASSIGNMENT = "NAME_ASSIGNMENT";
    static final String NEXT_ASSEMBLY_USAGE_OCCURRENCE = "NEXT_ASSEMBLY_USAGE_OCCURRENCE";
    static final String NODE = "NODE";
    static final String NODE_DEFINITION = "NODE_DEFINITION";
    static final String NODE_GROUP = "NODE_GROUP";
    static final String NODE_REPRESENTATION = "NODE_REPRESENTATION";
    static final String NODE_SET = "NODE_SET";
    static final String NODE_WITH_SOLUTION_COORDINATE_SYSTEM = "NODE_WITH_SOLUTION_COORDINATE_SYSTEM";
    static final String NODE_WITH_VECTOR = "NODE_WITH_VECTOR";
    static final String NON_MANIFOLD_SURFACE_SHAPE_REPRESENTATION = "NON_MANIFOLD_SURFACE_SHAPE_REPRESENTATION";
    static final String OBJECT_ROLE = "OBJECT_ROLE";
    static final String OFFSET_CURVE_3D = "OFFSET_CURVE_3D";
    static final String OFFSET_SURFACE = "OFFSET_SURFACE";
    static final String ONE_DIRECTION_REPEAT_FACTOR = "ONE_DIRECTION_REPEAT_FACTOR";
    static final String OPEN_SHELL = "OPEN_SHELL";
    static final String ORDINAL_DATE = "ORDINAL_DATE";
    static final String ORGANIZATION = "ORGANIZATION";
    static final String ORGANIZATIONAL_ADDRESS = "ORGANIZATIONAL_ADDRESS";
    static final String ORGANIZATION_ASSIGNMENT = "ORGANIZATION_ASSIGNMENT";
    static final String ORGANIZATION_ROLE = "ORGANIZATION_ROLE";
    static final String ORIENTED_CLOSED_SHELL = "ORIENTED_CLOSED_SHELL";
    static final String ORIENTED_EDGE = "ORIENTED_EDGE";
    static final String ORIENTED_FACE = "ORIENTED_FACE";
    static final String ORIENTED_OPEN_SHELL = "ORIENTED_OPEN_SHELL";
    static final String ORIENTED_PATH = "ORIENTED_PATH";
    static final String ORIENTED_SURFACE = "ORIENTED_SURFACE";
    static final String OUTER_BOUNDARY_CURVE = "OUTER_BOUNDARY_CURVE";
    static final String OVER_RIDING_STYLED_ITEM = "OVER_RIDING_STYLED_ITEM";
    static final String PARABOLA = "PARABOLA";
    static final String PARALLELISM_TOLERANCE = "PARALLELISM_TOLERANCE";
    static final String PARAMETRIC_CURVE_3D_ELEMENT_COORDINATE_DIRECTION = "PARAMETRIC_CURVE_3D_ELEMENT_COORDINATE_DIRECTION";
    static final String PARAMETRIC_CURVE_3D_ELEMENT_COORDINATE_SYSTEM = "PARAMETRIC_CURVE_3D_ELEMENT_COORDINATE_SYSTEM";
    static final String PARAMETRIC_REPRESENTATION_CONTEXT = "PARAMETRIC_REPRESENTATION_CONTEXT";
    static final String PARAMETRIC_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM = "PARAMETRIC_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM";
    static final String PATH = "PATH";
    static final String PATH_PARAMETRIC_REPRESENTATION_CONTEXT = "PATH_PARAMETRIC_REPRESENTATION_CONTEXT";
    static final String PCURVE = "PCURVE";
    static final String PERPENDICULARITY_TOLERANCE = "PERPENDICULARITY_TOLERANCE";
    static final String PERSON = "PERSON";
    static final String PERSONAL_ADDRESS = "PERSONAL_ADDRESS";
    static final String PERSON_AND_ORGANIZATION = "PERSON_AND_ORGANIZATION";
    static final String PERSON_AND_ORGANIZATION_ASSIGNMENT = "PERSON_AND_ORGANIZATION_ASSIGNMENT";
    static final String PERSON_AND_ORGANIZATION_ROLE = "PERSON_AND_ORGANIZATION_ROLE";
    static final String PHYSICALLY_MODELED_PRODUCT_DEFINITION = "PHYSICALLY_MODELED_PRODUCT_DEFINITION";
    static final String PLACED_DATUM_TARGET_FEATURE = "PLACED_DATUM_TARGET_FEATURE";
    static final String PLACEMENT = "PLACEMENT";
    static final String PLANAR_BOX = "PLANAR_BOX";
    static final String PLANAR_EXTENT = "PLANAR_EXTENT";
    static final String PLANE = "PLANE";
    static final String PLANE_ANGLE_MEASURE_WITH_UNIT = "PLANE_ANGLE_MEASURE_WITH_UNIT";
    static final String PLANE_ANGLE_UNIT = "PLANE_ANGLE_UNIT";
    static final String PLUS_MINUS_TOLERANCE = "PLUS_MINUS_TOLERANCE";
    static final String POINT = "POINT";
    static final String POINT_ON_CURVE = "POINT_ON_CURVE";
    static final String POINT_ON_SURFACE = "POINT_ON_SURFACE";
    static final String POINT_REPLICA = "POINT_REPLICA";
    static final String POINT_REPRESENTATION = "POINT_REPRESENTATION";
    static final String POINT_STYLE = "POINT_STYLE";
    static final String POLYLINE = "POLYLINE";
    static final String POLY_LOOP = "POLY_LOOP";
    static final String POSITION_TOLERANCE = "POSITION_TOLERANCE";
    static final String PRECISION_QUALIFIER = "PRECISION_QUALIFIER";
    static final String PRESENTATION_AREA = "PRESENTATION_AREA";
    static final String PRESENTATION_LAYER_ASSIGNMENT = "PRESENTATION_LAYER_ASSIGNMENT";
    static final String PRESENTATION_LAYER_USAGE = "PRESENTATION_LAYER_USAGE";
    static final String PRESENTATION_REPRESENTATION = "PRESENTATION_REPRESENTATION";
    static final String PRESENTATION_SET = "PRESENTATION_SET";
    static final String PRESENTATION_SIZE = "PRESENTATION_SIZE";
    static final String PRESENTATION_STYLE_ASSIGNMENT = "PRESENTATION_STYLE_ASSIGNMENT";
    static final String PRESENTATION_STYLE_BY_CONTEXT = "PRESENTATION_STYLE_BY_CONTEXT";
    static final String PRESENTATION_VIEW = "PRESENTATION_VIEW";
    static final String PRESENTED_ITEM = "PRESENTED_ITEM";
    static final String PRESENTED_ITEM_REPRESENTATION = "PRESENTED_ITEM_REPRESENTATION";
    static final String PRE_DEFINED_COLOUR = "PRE_DEFINED_COLOUR";
    static final String PRE_DEFINED_CURVE_FONT = "PRE_DEFINED_CURVE_FONT";
    static final String PRE_DEFINED_ITEM = "PRE_DEFINED_ITEM";
    static final String PRE_DEFINED_SYMBOL = "PRE_DEFINED_SYMBOL";
    static final String PRE_DEFINED_TEXT_FONT = "PRE_DEFINED_TEXT_FONT";
    static final String PRODUCT = "PRODUCT";
    static final String PRODUCT_CATEGORY = "PRODUCT_CATEGORY";
    static final String PRODUCT_CATEGORY_RELATIONSHIP = "PRODUCT_CATEGORY_RELATIONSHIP";
    static final String PRODUCT_CONCEPT = "PRODUCT_CONCEPT";
    static final String PRODUCT_CONCEPT_CONTEXT = "PRODUCT_CONCEPT_CONTEXT";
    static final String PRODUCT_CONTEXT = "PRODUCT_CONTEXT";
    static final String PRODUCT_DATA_REPRESENTATION_VIEW = "PRODUCT_DATA_REPRESENTATION_VIEW";
    static final String PRODUCT_DEFINITION = "PRODUCT_DEFINITION";
    static final String PRODUCT_DEFINITION_CONTEXT = "PRODUCT_DEFINITION_CONTEXT";
    static final String PRODUCT_DEFINITION_EFFECTIVITY = "PRODUCT_DEFINITION_EFFECTIVITY";
    static final String PRODUCT_DEFINITION_FORMATION = "PRODUCT_DEFINITION_FORMATION";
    static final String PRODUCT_DEFINITION_FORMATION_RELATIONSHIP = "PRODUCT_DEFINITION_FORMATION_RELATIONSHIP";
    static final String PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE = "PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE";
    static final String PRODUCT_DEFINITION_RELATIONSHIP = "PRODUCT_DEFINITION_RELATIONSHIP";
    static final String PRODUCT_DEFINITION_SHAPE = "PRODUCT_DEFINITION_SHAPE";
    static final String PRODUCT_DEFINITION_USAGE = "PRODUCT_DEFINITION_USAGE";
    static final String PRODUCT_DEFINITION_WITH_ASSOCIATED_DOCUMENTS = "PRODUCT_DEFINITION_WITH_ASSOCIATED_DOCUMENTS";
    static final String PRODUCT_RELATED_PRODUCT_CATEGORY = "PRODUCT_RELATED_PRODUCT_CATEGORY";
    static final String PRODUCT_TYPE = "PRODUCT_TYPE";
    static final String PROMISSORY_USAGE_OCCURRENCE = "PROMISSORY_USAGE_OCCURRENCE";
    static final String PROPERTY_DEFINITION = "PROPERTY_DEFINITION";
    static final String PROPERTY_DEFINITION_RELATIONSHIP = "PROPERTY_DEFINITION_RELATIONSHIP";
    static final String PROPERTY_DEFINITION_REPRESENTATION = "PROPERTY_DEFINITION_REPRESENTATION";
    static final String QUALIFIED_REPRESENTATION_ITEM = "QUALIFIED_REPRESENTATION_ITEM";
    static final String QUANTIFIED_ASSEMBLY_COMPONENT_USAGE = "QUANTIFIED_ASSEMBLY_COMPONENT_USAGE";
    static final String QUASI_UNIFORM_CURVE = "QUASI_UNIFORM_CURVE";
    static final String QUASI_UNIFORM_SURFACE = "QUASI_UNIFORM_SURFACE";
    static final String RATIONAL_B_SPLINE_CURVE = "RATIONAL_B_SPLINE_CURVE";
    static final String RATIONAL_B_SPLINE_SURFACE = "RATIONAL_B_SPLINE_SURFACE";
    static final String RATIO_MEASURE_WITH_UNIT = "RATIO_MEASURE_WITH_UNIT";
    static final String RATIO_UNIT = "RATIO_UNIT";
    static final String RECTANGULAR_COMPOSITE_SURFACE = "RECTANGULAR_COMPOSITE_SURFACE";
    static final String RECTANGULAR_TRIMMED_SURFACE = "RECTANGULAR_TRIMMED_SURFACE";
    static final String REPARAMETRISED_COMPOSITE_CURVE_SEGMENT = "REPARAMETRISED_COMPOSITE_CURVE_SEGMENT";
    static final String REPRESENTATION = "REPRESENTATION";
    static final String REPRESENTATION_CONTEXT = "REPRESENTATION_CONTEXT";
    static final String REPRESENTATION_ITEM = "REPRESENTATION_ITEM";
    static final String REPRESENTATION_MAP = "REPRESENTATION_MAP";
    static final String REPRESENTATION_RELATIONSHIP = "REPRESENTATION_RELATIONSHIP";
    static final String REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION = "REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION";
    static final String REP_ITEM_GROUP = "REP_ITEM_GROUP";
    static final String REVOLVED_AREA_SOLID = "REVOLVED_AREA_SOLID";
    static final String REVOLVED_FACE_SOLID = "REVOLVED_FACE_SOLID";
    static final String RIGHT_ANGULAR_WEDGE = "RIGHT_ANGULAR_WEDGE";
    static final String RIGHT_CIRCULAR_CONE = "RIGHT_CIRCULAR_CONE";
    static final String RIGHT_CIRCULAR_CYLINDER = "RIGHT_CIRCULAR_CYLINDER";
    static final String ROLE_ASSOCIATION = "ROLE_ASSOCIATION";
    static final String ROUNDNESS_TOLERANCE = "ROUNDNESS_TOLERANCE";
    static final String SEAM_CURVE = "SEAM_CURVE";
    static final String SEAM_EDGE = "SEAM_EDGE";
    static final String SECURITY_CLASSIFICATION = "SECURITY_CLASSIFICATION";
    static final String SECURITY_CLASSIFICATION_ASSIGNMENT = "SECURITY_CLASSIFICATION_ASSIGNMENT";
    static final String SECURITY_CLASSIFICATION_LEVEL = "SECURITY_CLASSIFICATION_LEVEL";
    static final String SHAPE_ASPECT = "SHAPE_ASPECT";
    static final String SHAPE_ASPECT_DERIVING_RELATIONSHIP = "SHAPE_ASPECT_DERIVING_RELATIONSHIP";
    static final String SHAPE_ASPECT_RELATIONSHIP = "SHAPE_ASPECT_RELATIONSHIP";
    static final String SHAPE_ASPECT_TRANSITION = "SHAPE_ASPECT_TRANSITION";
    static final String SHAPE_DEFINITION_REPRESENTATION = "SHAPE_DEFINITION_REPRESENTATION";
    static final String SHAPE_DIMENSION_REPRESENTATION = "SHAPE_DIMENSION_REPRESENTATION";
    static final String SHAPE_REPRESENTATION = "SHAPE_REPRESENTATION";
    static final String SHAPE_REPRESENTATION_RELATIONSHIP = "SHAPE_REPRESENTATION_RELATIONSHIP";
    static final String SHAPE_REPRESENTATION_WITH_PARAMETERS = "SHAPE_REPRESENTATION_WITH_PARAMETERS";
    static final String SHELL_BASED_SURFACE_MODEL = "SHELL_BASED_SURFACE_MODEL";
    static final String SI_UNIT = "SI_UNIT";
    static final String SOLID_ANGLE_MEASURE_WITH_UNIT = "SOLID_ANGLE_MEASURE_WITH_UNIT";
    static final String SOLID_ANGLE_UNIT = "SOLID_ANGLE_UNIT";
    static final String SOLID_MODEL = "SOLID_MODEL";
    static final String SOLID_REPLICA = "SOLID_REPLICA";
    static final String SPECIFIED_HIGHER_USAGE_OCCURRENCE = "SPECIFIED_HIGHER_USAGE_OCCURRENCE";
    static final String SPHERE = "SPHERE";
    static final String SPHERICAL_SURFACE = "SPHERICAL_SURFACE";
    static final String START_REQUEST = "START_REQUEST";
    static final String START_WORK = "START_WORK";
    static final String STRAIGHTNESS_TOLERANCE = "STRAIGHTNESS_TOLERANCE";
    static final String STRUCTURAL_RESPONSE_PROPERTY = "STRUCTURAL_RESPONSE_PROPERTY";
    static final String STRUCTURAL_RESPONSE_PROPERTY_DEFINITION_REPRESENTATION = "STRUCTURAL_RESPONSE_PROPERTY_DEFINITION_REPRESENTATION";
    static final String STYLED_ITEM = "STYLED_ITEM";
    static final String SUBEDGE = "SUBEDGE";
    static final String SUBFACE = "SUBFACE";
    static final String SUPPLIED_PART_RELATIONSHIP = "SUPPLIED_PART_RELATIONSHIP";
    static final String SURFACE = "SURFACE";
    static final String SURFACE_3D_ELEMENT_DESCRIPTOR = "SURFACE_3D_ELEMENT_DESCRIPTOR";
    static final String SURFACE_3D_ELEMENT_REPRESENTATION = "SURFACE_3D_ELEMENT_REPRESENTATION";
    static final String SURFACE_CURVE = "SURFACE_CURVE";
    static final String SURFACE_ELEMENT_PROPERTY = "SURFACE_ELEMENT_PROPERTY";
    static final String SURFACE_OF_LINEAR_EXTRUSION = "SURFACE_OF_LINEAR_EXTRUSION";
    static final String SURFACE_OF_REVOLUTION = "SURFACE_OF_REVOLUTION";
    static final String SURFACE_PATCH = "SURFACE_PATCH";
    static final String SURFACE_PROFILE_TOLERANCE = "SURFACE_PROFILE_TOLERANCE";
    static final String SURFACE_REPLICA = "SURFACE_REPLICA";
    static final String SURFACE_SECTION = "SURFACE_SECTION";
    static final String SURFACE_SECTION_FIELD = "SURFACE_SECTION_FIELD";
    static final String SURFACE_SECTION_FIELD_CONSTANT = "SURFACE_SECTION_FIELD_CONSTANT";
    static final String SURFACE_SECTION_FIELD_VARYING = "SURFACE_SECTION_FIELD_VARYING";
    static final String SURFACE_SIDE_STYLE = "SURFACE_SIDE_STYLE";
    static final String SURFACE_STYLE_BOUNDARY = "SURFACE_STYLE_BOUNDARY";
    static final String SURFACE_STYLE_CONTROL_GRID = "SURFACE_STYLE_CONTROL_GRID";
    static final String SURFACE_STYLE_FILL_AREA = "SURFACE_STYLE_FILL_AREA";
    static final String SURFACE_STYLE_PARAMETER_LINE = "SURFACE_STYLE_PARAMETER_LINE";
    static final String SURFACE_STYLE_SEGMENTATION_CURVE = "SURFACE_STYLE_SEGMENTATION_CURVE";
    static final String SURFACE_STYLE_SILHOUETTE = "SURFACE_STYLE_SILHOUETTE";
    static final String SURFACE_STYLE_USAGE = "SURFACE_STYLE_USAGE";
    static final String SWEPT_AREA_SOLID = "SWEPT_AREA_SOLID";
    static final String SWEPT_FACE_SOLID = "SWEPT_FACE_SOLID";
    static final String SWEPT_SURFACE = "SWEPT_SURFACE";
    static final String SYMBOL_COLOUR = "SYMBOL_COLOUR";
    static final String SYMBOL_REPRESENTATION = "SYMBOL_REPRESENTATION";
    static final String SYMBOL_REPRESENTATION_MAP = "SYMBOL_REPRESENTATION_MAP";
    static final String SYMBOL_STYLE = "SYMBOL_STYLE";
    static final String SYMBOL_TARGET = "SYMBOL_TARGET";
    static final String SYMMETRY_TOLERANCE = "SYMMETRY_TOLERANCE";
    static final String TEMPLATE = "TEMPLATE";
    static final String TEMPLATE_INSTANCE = "TEMPLATE_INSTANCE";
    static final String TERMINATOR_SYMBOL = "TERMINATOR_SYMBOL";
    static final String TEXT_LITERAL = "TEXT_LITERAL";
    static final String TEXT_LITERAL_WITH_ASSOCIATED_CURVES = "TEXT_LITERAL_WITH_ASSOCIATED_CURVES";
    static final String TEXT_LITERAL_WITH_BLANKING_BOX = "TEXT_LITERAL_WITH_BLANKING_BOX";
    static final String TEXT_LITERAL_WITH_DELINEATION = "TEXT_LITERAL_WITH_DELINEATION";
    static final String TEXT_LITERAL_WITH_EXTENT = "TEXT_LITERAL_WITH_EXTENT";
    static final String TEXT_STYLE = "TEXT_STYLE";
    static final String TEXT_STYLE_FOR_DEFINED_FONT = "TEXT_STYLE_FOR_DEFINED_FONT";
    static final String TEXT_STYLE_WITH_BOX_CHARACTERISTICS = "TEXT_STYLE_WITH_BOX_CHARACTERISTICS";
    static final String TEXT_STYLE_WITH_MIRROR = "TEXT_STYLE_WITH_MIRROR";
    static final String THERMODYNAMIC_TEMPERATURE_UNIT = "THERMODYNAMIC_TEMPERATURE_UNIT";
    static final String TIME_MEASURE_WITH_UNIT = "TIME_MEASURE_WITH_UNIT";
    static final String TIME_UNIT = "TIME_UNIT";
    static final String TOLERANCE_VALUE = "TOLERANCE_VALUE";
    static final String TOPOLOGICAL_REPRESENTATION_ITEM = "TOPOLOGICAL_REPRESENTATION_ITEM";
    static final String TOROIDAL_SURFACE = "TOROIDAL_SURFACE";
    static final String TORUS = "TORUS";
    static final String TOTAL_RUNOUT_TOLERANCE = "TOTAL_RUNOUT_TOLERANCE";
    static final String TRANSITIONAL_SHAPE_REPRESENTATION = "TRANSITIONAL_SHAPE_REPRESENTATION";
    static final String TRIMMED_CURVE = "TRIMMED_CURVE";
    static final String TWO_DIRECTION_REPEAT_FACTOR = "TWO_DIRECTION_REPEAT_FACTOR";
    static final String TYPE_QUALIFIER = "TYPE_QUALIFIER";
    static final String UNCERTAINTY_MEASURE_WITH_UNIT = "UNCERTAINTY_MEASURE_WITH_UNIT";
    static final String UNIFORM_CURVE = "UNIFORM_CURVE";
    static final String UNIFORM_SURFACE = "UNIFORM_SURFACE";
    static final String UNIFORM_SURFACE_SECTION = "UNIFORM_SURFACE_SECTION";
    static final String VALUE_RANGE = "VALUE_RANGE";
    static final String VECTOR = "VECTOR";
    static final String VERSIONED_ACTION_REQUEST = "VERSIONED_ACTION_REQUEST";
    static final String VERTEX = "VERTEX";
    static final String VERTEX_LOOP = "VERTEX_LOOP";
    static final String VERTEX_POINT = "VERTEX_POINT";
    static final String VIEW_VOLUME = "VIEW_VOLUME";
    static final String VOLUME_3D_ELEMENT_DESCRIPTOR = "VOLUME_3D_ELEMENT_DESCRIPTOR";
    static final String VOLUME_3D_ELEMENT_REPRESENTATION = "VOLUME_3D_ELEMENT_REPRESENTATION";
    static final String VOLUME_UNIT = "VOLUME_UNIT";
    static final String WEEK_OF_YEAR_AND_DAY_DATE = "WEEK_OF_YEAR_AND_DAY_DATE";

    public static final String[] ALL = {
            ACTION,
            ACTION_ASSIGNMENT,
            ACTION_METHOD,
            ACTION_REQUEST_ASSIGNMENT,
            ACTION_REQUEST_SOLUTION,
            ADDRESS,
            ADVANCED_BREP_SHAPE_REPRESENTATION,
            ADVANCED_FACE,
            ALIGNED_CURVE_3D_ELEMENT_COORDINATE_SYSTEM,
            ALIGNED_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM,
            ANALYSIS_ITEM_WITHIN_REPRESENTATION,
            ANGULARITY_TOLERANCE,
            ANGULAR_LOCATION,
            ANGULAR_SIZE,
            ANNOTATION_CURVE_OCCURRENCE,
            ANNOTATION_FILL_AREA,
            ANNOTATION_FILL_AREA_OCCURRENCE,
            ANNOTATION_OCCURRENCE,
            ANNOTATION_SUBFIGURE_OCCURRENCE,
            ANNOTATION_SYMBOL,
            ANNOTATION_SYMBOL_OCCURRENCE,
            ANNOTATION_TEXT,
            ANNOTATION_TEXT_OCCURRENCE,
            APPLICATION_CONTEXT,
            APPLICATION_CONTEXT_ELEMENT,
            APPLICATION_PROTOCOL_DEFINITION,
            APPLIED_APPROVAL_ASSIGNMENT,
            APPLIED_DATE_AND_TIME_ASSIGNMENT,
            APPLIED_DATE_ASSIGNMENT,
            APPLIED_DOCUMENT_REFERENCE,
            APPLIED_EXTERNAL_IDENTIFICATION_ASSIGNMENT,
            APPLIED_GROUP_ASSIGNMENT,
            APPLIED_ORGANIZATION_ASSIGNMENT,
            APPLIED_PERSON_AND_ORGANIZATION_ASSIGNMENT,
            APPLIED_PRESENTED_ITEM,
            APPLIED_SECURITY_CLASSIFICATION_ASSIGNMENT,
            APPROVAL,
            APPROVAL_ASSIGNMENT,
            APPROVAL_DATE_TIME,
            APPROVAL_PERSON_ORGANIZATION,
            APPROVAL_RELATIONSHIP,
            APPROVAL_ROLE,
            APPROVAL_STATUS,
            ARBITRARY_VOLUME_3D_ELEMENT_COORDINATE_SYSTEM,
            AREA_IN_SET,
            AREA_UNIT,
            ASSEMBLY_COMPONENT_USAGE,
            ASSEMBLY_COMPONENT_USAGE_SUBSTITUTE,
            AUTO_DESIGN_ACTUAL_DATE_AND_TIME_ASSIGNMENT,
            AUTO_DESIGN_ACTUAL_DATE_ASSIGNMENT,
            AUTO_DESIGN_APPROVAL_ASSIGNMENT,
            AUTO_DESIGN_DATE_AND_PERSON_ASSIGNMENT,
            AUTO_DESIGN_DOCUMENT_REFERENCE,
            AUTO_DESIGN_GROUP_ASSIGNMENT,
            AUTO_DESIGN_NOMINAL_DATE_AND_TIME_ASSIGNMENT,
            AUTO_DESIGN_NOMINAL_DATE_ASSIGNMENT,
            AUTO_DESIGN_ORGANIZATION_ASSIGNMENT,
            AUTO_DESIGN_PERSON_AND_ORGANIZATION_ASSIGNMENT,
            AUTO_DESIGN_PRESENTED_ITEM,
            AUTO_DESIGN_SECURITY_CLASSIFICATION_ASSIGNMENT,
            AUTO_DESIGN_VIEW_AREA,
            AXIS1_PLACEMENT,
            AXIS2_PLACEMENT_2D,
            AXIS2_PLACEMENT_3D,
            BACKGROUND_COLOUR,
            BEZIER_CURVE,
            BEZIER_SURFACE,
            BLOCK,
            BOOLEAN_RESULT,
            BOUNDARY_CURVE,
            BOUNDED_CURVE,
            BOUNDED_SURFACE,
            BOXED_HALF_SPACE,
            BOX_DOMAIN,
            BREP_WITH_VOIDS,
            B_SPLINE_CURVE,
            B_SPLINE_CURVE_WITH_KNOTS,
            B_SPLINE_SURFACE,
            B_SPLINE_SURFACE_WITH_KNOTS,
            CALENDAR_DATE,
            CAMERA_IMAGE,
            CAMERA_IMAGE_2D_WITH_SCALE,
            CAMERA_IMAGE_3D_WITH_SCALE,
            CAMERA_MODEL,
            CAMERA_MODEL_D2,
            CAMERA_MODEL_D3,
            CAMERA_USAGE,
            CARTESIAN_POINT,
            CARTESIAN_TRANSFORMATION_OPERATOR,
            CARTESIAN_TRANSFORMATION_OPERATOR_2D,
            CARTESIAN_TRANSFORMATION_OPERATOR_3D,
            CC_DESIGN_APPROVAL,
            CC_DESIGN_CERTIFICATION,
            CC_DESIGN_CONTRACT,
            CC_DESIGN_DATE_AND_TIME_ASSIGNMENT,
            CC_DESIGN_PERSON_AND_ORGANIZATION_ASSIGNMENT,
            CC_DESIGN_SECURITY_CLASSIFICATION,
            CC_DESIGN_SPECIFICATION_REFERENCE,
            CERTIFICATION,
            CERTIFICATION_ASSIGNMENT,
            CERTIFICATION_TYPE,
            CHANGE,
            CHANGE_REQUEST,
            CHARACTERIZED_OBJECT,
            CIRCLE,
            CIRCULAR_RUNOUT_TOLERANCE,
            CLASS,
            CLOSED_SHELL,
            COAXIALITY_TOLERANCE,
            COLOUR,
            COLOUR_RGB,
            COLOUR_SPECIFICATION,
            COMMON_DATUM,
            COMPOSITE_CURVE,
            COMPOSITE_CURVE_ON_SURFACE,
            COMPOSITE_CURVE_SEGMENT,
            COMPOSITE_SHAPE_ASPECT,
            COMPOSITE_TEXT,
            COMPOSITE_TEXT_WITH_ASSOCIATED_CURVES,
            COMPOSITE_TEXT_WITH_BLANKING_BOX,
            COMPOSITE_TEXT_WITH_EXTENT,
            COMPOUND_REPRESENTATION_ITEM,
            COMPOUND_SHAPE_REPRESENTATION,
            CONCENTRICITY_TOLERANCE,
            CONFIGURATION_DESIGN,
            CONFIGURATION_EFFECTIVITY,
            CONIC,
            CONICAL_SURFACE,
            CONNECTED_EDGE_SET,
            CONNECTED_FACE_SET,
            CONNECTED_FACE_SHAPE_REPRESENTATION,
            CONNECTED_FACE_SUB_SET,
            CONSTANT_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM,
            CONTEXT_DEPENDENT_INVISIBILITY,
            CONTEXT_DEPENDENT_OVER_RIDING_STYLED_ITEM,
            CONTEXT_DEPENDENT_SHAPE_REPRESENTATION,
            CONTRACT,
            CONTRACT_ASSIGNMENT,
            CONTRACT_TYPE,
            CONVERSION_BASED_UNIT,
            COORDINATED_UNIVERSAL_TIME_OFFSET,
            CSG_REPRESENTATION,
            CSG_SHAPE_REPRESENTATION,
            CSG_SOLID,
            CURVE,
            CURVE_3D_ELEMENT_DESCRIPTOR,
            CURVE_3D_ELEMENT_PROPERTY,
            CURVE_3D_ELEMENT_REPRESENTATION,
            CURVE_BOUNDED_SURFACE,
            CURVE_ELEMENT_END_OFFSET,
            CURVE_ELEMENT_END_RELEASE,
            CURVE_ELEMENT_END_RELEASE_PACKET,
            CURVE_ELEMENT_INTERVAL,
            CURVE_ELEMENT_INTERVAL_CONSTANT,
            CURVE_ELEMENT_INTERVAL_LINEARLY_VARYING,
            CURVE_ELEMENT_LOCATION,
            CURVE_ELEMENT_SECTION_DEFINITION,
            CURVE_ELEMENT_SECTION_DERIVED_DEFINITIONS,
            CURVE_REPLICA,
            CURVE_STYLE,
            CURVE_STYLE_FONT,
            CURVE_STYLE_FONT_PATTERN,
            CYLINDRICAL_SURFACE,
            DATA_ENVIRONMENT,
            DATE,
            DATE_AND_TIME,
            DATE_AND_TIME_ASSIGNMENT,
            DATE_ASSIGNMENT,
            DATE_ROLE,
            DATE_TIME_ROLE,
            DATUM,
            DATUM_FEATURE,
            DATUM_REFERENCE,
            DATUM_TARGET,
            DEFINED_SYMBOL,
            DEFINITIONAL_REPRESENTATION,
            DEGENERATE_PCURVE,
            DEGENERATE_TOROIDAL_SURFACE,
            DERIVED_SHAPE_ASPECT,
            DERIVED_UNIT,
            DERIVED_UNIT_ELEMENT,
            DESCRIPTIVE_REPRESENTATION_ITEM,
            DESIGN_CONTEXT,
            DIGITAL_DOCUMENT,
            DIMENSIONAL_CHARACTERISTIC_REPRESENTATION,
            DIMENSIONAL_EXPONENTS,
            DIMENSIONAL_LOCATION,
            DIMENSIONAL_LOCATION_WITH_PATH,
            DIMENSIONAL_SIZE,
            DIMENSIONAL_SIZE_WITH_PATH,
            DIMENSION_CURVE,
            DIMENSION_CURVE_TERMINATOR,
            DIRECTED_DIMENSIONAL_LOCATION,
            DIRECTION,
            DOCUMENT,
            DOCUMENT_FILE,
            DOCUMENT_PRODUCT_ASSOCIATION,
            DOCUMENT_PRODUCT_EQUIVALENCE,
            DOCUMENT_RELATIONSHIP,
            DOCUMENT_REPRESENTATION_TYPE,
            DOCUMENT_TYPE,
            DOCUMENT_USAGE_CONSTRAINT,
            DRAUGHTING_ANNOTATION_OCCURRENCE,
            DRAUGHTING_CALLOUT,
            DRAUGHTING_MODEL,
            DRAUGHTING_PRE_DEFINED_COLOUR,
            DRAUGHTING_PRE_DEFINED_CURVE_FONT,
            DRAUGHTING_SUBFIGURE_REPRESENTATION,
            DRAUGHTING_SYMBOL_REPRESENTATION,
            DRAUGHTING_TEXT_LITERAL_WITH_DELINEATION,
            DRAWING_DEFINITION,
            DRAWING_REVISION,
            DUMMY_NODE,
            EDGE,
            EDGE_BASED_WIREFRAME_MODEL,
            EDGE_BASED_WIREFRAME_SHAPE_REPRESENTATION,
            EDGE_CURVE,
            EDGE_LOOP,
            EFFECTIVITY,
            EFFECTIVITY_ASSIGNMENT,
            ELEMENTARY_SURFACE,
            ELEMENT_DESCRIPTOR,
            ELEMENT_GEOMETRIC_RELATIONSHIP,
            ELEMENT_GROUP,
            ELEMENT_MATERIAL,
            ELEMENT_REPRESENTATION,
            ELLIPSE,
            EULER_ANGLES,
            EVALUATED_DEGENERATE_PCURVE,
            EXTENSION,
            EXTERNALLY_DEFINED_CURVE_FONT,
            EXTERNALLY_DEFINED_Class,
            EXTERNALLY_DEFINED_GENERAL_PROPERTY,
            EXTERNALLY_DEFINED_HATCH_STYLE,
            EXTERNALLY_DEFINED_ITEM,
            EXTERNALLY_DEFINED_REPRESENTATION,
            EXTERNALLY_DEFINED_SYMBOL,
            EXTERNALLY_DEFINED_TEXT_FONT,
            EXTERNALLY_DEFINED_TILE_STYLE,
            EXTERNAL_IDENTIFICATION_ASSIGNMENT,
            EXTERNAL_SOURCE,
            EXTRUDED_AREA_SOLID,
            EXTRUDED_FACE_SOLID,
            FACE,
            FACETED_BREP,
            FACETED_BREP_SHAPE_REPRESENTATION,
            FACE_BASED_SURFACE_MODEL,
            FACE_BOUND,
            FACE_OUTER_BOUND,
            FACE_SURFACE,
            FEA_AREA_DENSITY,
            FEA_AXIS2_PLACEMENT_3D,
            FEA_CURVE_SECTION_GEOMETRIC_RELATIONSHIP,
            FEA_GROUP,
            FEA_LINEAR_ELASTICITY,
            FEA_MASS_DENSITY,
            FEA_MATERIAL_PROPERTY_REPRESENTATION,
            FEA_MATERIAL_PROPERTY_REPRESENTATION_ITEM,
            FEA_MODEL,
            FEA_MODEL_3D,
            FEA_MODEL_DEFINITION,
            FEA_MODEL_DEFINITION,
            FEA_MOISTURE_ABSORPTION,
            FEA_PARAMETRIC_POINT,
            FEA_REPRESENTATION_ITEM,
            FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION,
            FEA_SHELL_BENDING_STIFFNESS,
            FEA_SHELL_MEMBRANE_BENDING_COUPLING_STIFFNESS,
            FEA_SHELL_MEMBRANE_STIFFNESS,
            FEA_SHELL_SHEAR_STIFFNESS,
            FEA_SURFACE_SECTION_GEOMETRIC_RELATIONSHIP,
            FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION,
            FILL_AREA_STYLE,
            FILL_AREA_STYLE_COLOUR,
            FILL_AREA_STYLE_HATCHING,
            FILL_AREA_STYLE_TILES,
            FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE,
            FLATNESS_TOLERANCE,
            FREEDOMS_LIST,
            FREEDOM_AND_COEFFICIENT,
            FUNCTIONALLY_DEFINED_TRANSFORMATION,
            GENERAL_PROPERTY,
            GEOMETRICALLY_BOUNDED_SURFACE_SHAPE_REPRESENTATION,
            GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION,
            GEOMETRIC_CURVE_SET,
            GEOMETRIC_NODE,
            GEOMETRIC_REPRESENTATION_CONTEXT,
            GEOMETRIC_REPRESENTATION_ITEM,
            GEOMETRIC_SET,
            GEOMETRIC_TOLERANCE,
            GEOMETRIC_TOLERANCE_RELATIONSHIP,
            GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE,
            GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT,
            GLOBAL_UNIT_ASSIGNED_CONTEXT,
            GROUP,
            GROUP_ASSIGNMENT,
            GROUP_RELATIONSHIP,
            HALF_SPACE_SOLID,
            HYPERBOLA,
            IDENTIFICATION_ASSIGNMENT,
            IDENTIFICATION_ROLE,
            INTERSECTION_CURVE,
            INVISIBILITY,
            ITEM_DEFINED_TRANSFORMATION,
            LENGTH_MEASURE_WITH_UNIT,
            LENGTH_UNIT,
            LIMITS_AND_FITS,
            LINE,
            LINE_PROFILE_TOLERANCE,
            LOCAL_TIME,
            LOOP,
            MAKE_FROM_USAGE_OPTION,
            MANIFOLD_SOLID_BREP,
            MANIFOLD_SURFACE_SHAPE_REPRESENTATION,
            MAPPED_ITEM,
            MASS_MEASURE_WITH_UNIT,
            MASS_UNIT,
            MATERIAL_DESIGNATION,
            MATERIAL_PROPERTY,
            MATERIAL_PROPERTY_REPRESENTATION,
            MEASURE_QUALIFICATION,
            MEASURE_REPRESENTATION_ITEM,
            MEASURE_WITH_UNIT,
            MECHANICAL_CONTEXT,
            MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_AREA,
            MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION,
            MECHANICAL_DESIGN_PRESENTATION_AREA,
            MODIFIED_GEOMETRIC_TOLERANCE,
            NAMED_UNIT,
            NAME_ASSIGNMENT,
            NEXT_ASSEMBLY_USAGE_OCCURRENCE,
            NODE,
            NODE_DEFINITION,
            NODE_GROUP,
            NODE_REPRESENTATION,
            NODE_SET,
            NODE_WITH_SOLUTION_COORDINATE_SYSTEM,
            NODE_WITH_VECTOR,
            NON_MANIFOLD_SURFACE_SHAPE_REPRESENTATION,
            OBJECT_ROLE,
            OFFSET_CURVE_3D,
            OFFSET_SURFACE,
            ONE_DIRECTION_REPEAT_FACTOR,
            OPEN_SHELL,
            ORDINAL_DATE,
            ORGANIZATION,
            ORGANIZATIONAL_ADDRESS,
            ORGANIZATION_ASSIGNMENT,
            ORGANIZATION_ROLE,
            ORIENTED_CLOSED_SHELL,
            ORIENTED_EDGE,
            ORIENTED_FACE,
            ORIENTED_OPEN_SHELL,
            ORIENTED_PATH,
            ORIENTED_SURFACE,
            OUTER_BOUNDARY_CURVE,
            OVER_RIDING_STYLED_ITEM,
            PARABOLA,
            PARALLELISM_TOLERANCE,
            PARAMETRIC_CURVE_3D_ELEMENT_COORDINATE_DIRECTION,
            PARAMETRIC_CURVE_3D_ELEMENT_COORDINATE_SYSTEM,
            PARAMETRIC_REPRESENTATION_CONTEXT,
            PARAMETRIC_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM,
            PATH,
            PCURVE,
            PERPENDICULARITY_TOLERANCE,
            PERSON,
            PERSONAL_ADDRESS,
            PERSON_AND_ORGANIZATION,
            PERSON_AND_ORGANIZATION_ASSIGNMENT,
            PERSON_AND_ORGANIZATION_ROLE,
            PHYSICALLY_MODELED_PRODUCT_DEFINITION,
            PLACED_DATUM_TARGET_FEATURE,
            PLACEMENT,
            PLANAR_BOX,
            PLANAR_EXTENT,
            PLANE,
            PLANE_ANGLE_MEASURE_WITH_UNIT,
            PLANE_ANGLE_UNIT,
            PLUS_MINUS_TOLERANCE,
            POINT,
            POINT_ON_CURVE,
            POINT_ON_SURFACE,
            POINT_REPLICA,
            POINT_REPRESENTATION,
            POINT_STYLE,
            POLYLINE,
            POLY_LOOP,
            POSITION_TOLERANCE,
            PRECISION_QUALIFIER,
            PRESENTATION_AREA,
            PRESENTATION_LAYER_ASSIGNMENT,
            PRESENTATION_LAYER_USAGE,
            PRESENTATION_REPRESENTATION,
            PRESENTATION_SET,
            PRESENTATION_SIZE,
            PRESENTATION_STYLE_ASSIGNMENT,
            PRESENTATION_STYLE_BY_CONTEXT,
            PRESENTATION_VIEW,
            PRESENTED_ITEM,
            PRESENTED_ITEM_REPRESENTATION,
            PRE_DEFINED_COLOUR,
            PRE_DEFINED_CURVE_FONT,
            PRE_DEFINED_ITEM,
            PRE_DEFINED_SYMBOL,
            PRE_DEFINED_TEXT_FONT,
            PRODUCT,
            PRODUCT_CATEGORY,
            PRODUCT_CATEGORY_RELATIONSHIP,
            PRODUCT_CONCEPT,
            PRODUCT_CONCEPT_CONTEXT,
            PRODUCT_CONTEXT,
            PRODUCT_DATA_REPRESENTATION_VIEW,
            PRODUCT_DEFINITION,
            PRODUCT_DEFINITION_CONTEXT,
            PRODUCT_DEFINITION_EFFECTIVITY,
            PRODUCT_DEFINITION_FORMATION,
            PRODUCT_DEFINITION_FORMATION_RELATIONSHIP,
            PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE,
            PRODUCT_DEFINITION_RELATIONSHIP,
            PRODUCT_DEFINITION_SHAPE,
            PRODUCT_DEFINITION_USAGE,
            PRODUCT_DEFINITION_WITH_ASSOCIATED_DOCUMENTS,
            PRODUCT_RELATED_PRODUCT_CATEGORY,
            PRODUCT_TYPE,
            PROMISSORY_USAGE_OCCURRENCE,
            PROPERTY_DEFINITION,
            PROPERTY_DEFINITION_RELATIONSHIP,
            PROPERTY_DEFINITION_REPRESENTATION,
            QUALIFIED_REPRESENTATION_ITEM,
            QUANTIFIED_ASSEMBLY_COMPONENT_USAGE,
            QUASI_UNIFORM_CURVE,
            QUASI_UNIFORM_SURFACE,
            RATIONAL_B_SPLINE_CURVE,
            RATIONAL_B_SPLINE_SURFACE,
            RATIO_MEASURE_WITH_UNIT,
            RATIO_UNIT,
            RECTANGULAR_COMPOSITE_SURFACE,
            RECTANGULAR_TRIMMED_SURFACE,
            REPARAMETRISED_COMPOSITE_CURVE_SEGMENT,
            REPRESENTATION,
            REPRESENTATION_CONTEXT,
            REPRESENTATION_ITEM,
            REPRESENTATION_MAP,
            REPRESENTATION_RELATIONSHIP,
            REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION,
            REP_ITEM_GROUP,
            REVOLVED_AREA_SOLID,
            REVOLVED_FACE_SOLID,
            RIGHT_ANGULAR_WEDGE,
            RIGHT_CIRCULAR_CONE,
            RIGHT_CIRCULAR_CYLINDER,
            ROLE_ASSOCIATION,
            ROUNDNESS_TOLERANCE,
            SEAM_CURVE,
            SEAM_EDGE,
            SECURITY_CLASSIFICATION,
            SECURITY_CLASSIFICATION_ASSIGNMENT,
            SECURITY_CLASSIFICATION_LEVEL,
            SHAPE_ASPECT,
            SHAPE_ASPECT_DERIVING_RELATIONSHIP,
            SHAPE_ASPECT_RELATIONSHIP,
            SHAPE_ASPECT_TRANSITION,
            SHAPE_DEFINITION_REPRESENTATION,
            SHAPE_DIMENSION_REPRESENTATION,
            SHAPE_REPRESENTATION,
            SHAPE_REPRESENTATION_RELATIONSHIP,
            SHAPE_REPRESENTATION_WITH_PARAMETERS,
            SHELL_BASED_SURFACE_MODEL,
            SI_UNIT,
            SOLID_ANGLE_MEASURE_WITH_UNIT,
            SOLID_ANGLE_UNIT,
            SOLID_MODEL,
            SOLID_REPLICA,
            SPECIFIED_HIGHER_USAGE_OCCURRENCE,
            SPHERE,
            SPHERICAL_SURFACE,
            START_REQUEST,
            START_WORK,
            STRAIGHTNESS_TOLERANCE,
            STRUCTURAL_RESPONSE_PROPERTY,
            STRUCTURAL_RESPONSE_PROPERTY_DEFINITION_REPRESENTATION,
            STYLED_ITEM,
            SUBEDGE,
            SUBFACE,
            SUPPLIED_PART_RELATIONSHIP,
            SURFACE,
            SURFACE_3D_ELEMENT_DESCRIPTOR,
            SURFACE_3D_ELEMENT_REPRESENTATION,
            SURFACE_CURVE,
            SURFACE_ELEMENT_PROPERTY,
            SURFACE_OF_LINEAR_EXTRUSION,
            SURFACE_OF_REVOLUTION,
            SURFACE_PATCH,
            SURFACE_PROFILE_TOLERANCE,
            SURFACE_REPLICA,
            SURFACE_SECTION,
            SURFACE_SECTION_FIELD,
            SURFACE_SECTION_FIELD_CONSTANT,
            SURFACE_SECTION_FIELD_VARYING,
            SURFACE_SIDE_STYLE,
            SURFACE_STYLE_BOUNDARY,
            SURFACE_STYLE_CONTROL_GRID,
            SURFACE_STYLE_FILL_AREA,
            SURFACE_STYLE_PARAMETER_LINE,
            SURFACE_STYLE_SEGMENTATION_CURVE,
            SURFACE_STYLE_SILHOUETTE,
            SURFACE_STYLE_USAGE,
            SWEPT_AREA_SOLID,
            SWEPT_FACE_SOLID,
            SWEPT_SURFACE,
            SYMBOL_COLOUR,
            SYMBOL_REPRESENTATION,
            SYMBOL_REPRESENTATION_MAP,
            SYMBOL_STYLE,
            SYMBOL_TARGET,
            SYMMETRY_TOLERANCE,
            TEMPLATE,
            TEMPLATE_INSTANCE,
            TERMINATOR_SYMBOL,
            TEXT_LITERAL,
            TEXT_LITERAL_WITH_ASSOCIATED_CURVES,
            TEXT_LITERAL_WITH_BLANKING_BOX,
            TEXT_LITERAL_WITH_DELINEATION,
            TEXT_LITERAL_WITH_EXTENT,
            TEXT_STYLE,
            TEXT_STYLE_FOR_DEFINED_FONT,
            TEXT_STYLE_WITH_BOX_CHARACTERISTICS,
            TEXT_STYLE_WITH_MIRROR,
            THERMODYNAMIC_TEMPERATURE_UNIT,
            TIME_MEASURE_WITH_UNIT,
            TIME_UNIT,
            TOLERANCE_VALUE,
            TOPOLOGICAL_REPRESENTATION_ITEM,
            TOROIDAL_SURFACE,
            TORUS,
            TOTAL_RUNOUT_TOLERANCE,
            TRANSITIONAL_SHAPE_REPRESENTATION,
            TRIMMED_CURVE,
            TWO_DIRECTION_REPEAT_FACTOR,
            TYPE_QUALIFIER,
            UNCERTAINTY_MEASURE_WITH_UNIT,
            UNIFORM_CURVE,
            UNIFORM_SURFACE,
            UNIFORM_SURFACE_SECTION,
            VALUE_RANGE,
            VECTOR,
            VERSIONED_ACTION_REQUEST,
            VERTEX,
            VERTEX_LOOP,
            VERTEX_POINT,
            VIEW_VOLUME,
            VOLUME_3D_ELEMENT_DESCRIPTOR,
            VOLUME_3D_ELEMENT_REPRESENTATION,
            VOLUME_UNIT,
            WEEK_OF_YEAR_AND_DAY_DATE,
    };

    public static final String[] CONTEXTS = {
            ANALYSIS_REPRESENTATION_CONTEXT,
            GEOMETRIC_REPRESENTATION_CONTEXT,
            GEOMETRIC_REPRESENTATION_CONTEXT_WITH_PARAMETER,
            GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT,
            GLOBAL_UNIT_ASSIGNED_CONTEXT,
            PARAMETRIC_REPRESENTATION_CONTEXT,
            PATH_PARAMETRIC_REPRESENTATION_CONTEXT,
            REPRESENTATION_CONTEXT
    };

    public static final String[] UNITS = {
            NAMED_UNIT,
            SI_UNIT,
            CONVERSION_BASED_UNIT,
            LENGTH_UNIT,
            MASS_UNIT,
            TIME_UNIT,
            THERMODYNAMIC_TEMPERATURE_UNIT,
            PLANE_ANGLE_UNIT,
            SOLID_ANGLE_UNIT,
            RATIO_UNIT
    };
}
